language: node_js
node_js:
  - 12

before_script:
  - npm install -g gulp-cli
  - npm install
script: gulp build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  verbose: true
  on:
    branch: master
